"""empty message

Revision ID: 003395a27588
Revises: dba514422936
Create Date: 2023-10-27 16:11:04.329391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003395a27588'
down_revision = 'dba514422936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_photo', sa.String(), nullable=True))
        batch_op.drop_column('ktm_photo')
        batch_op.drop_column('ktp_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ktp_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ktm_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('card_photo')

    # ### end Alembic commands ###
