"""empty message

Revision ID: 2a78f085289f
Revises: 89012db4b257
Create Date: 2023-10-31 16:33:12.751283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a78f085289f'
down_revision = '89012db4b257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_image', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('Bahan', 'Alat', name='product_type'), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Tersedia', 'Tidak Tersedia', name='product_status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
