"""empty message

Revision ID: 3229b9f4a6bf
Revises: 
Create Date: 2023-10-22 16:49:01.320324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3229b9f4a6bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('no_hp', sa.String(), nullable=True),
    sa.Column('self_photo', sa.String(), nullable=True),
    sa.Column('ktm_photo', sa.String(), nullable=True),
    sa.Column('ktp_photo', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('Mahasiswa', 'Admin Lab', name='user_role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('no_hp'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
