"""empty message

Revision ID: 81f6f10a8976
Revises: d320a2dc0410
Create Date: 2023-11-04 08:59:19.428020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f6f10a8976'
down_revision = 'd320a2dc0410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('major')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
