"""empty message

Revision ID: c44b0eb3bf22
Revises: 62c94b9b4e24
Create Date: 2023-10-31 16:26:50.620529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44b0eb3bf22'
down_revision = '62c94b9b4e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Tersedia', 'Tidak Tersedia', name='product_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
