"""empty message

Revision ID: de136551882f
Revises: 81f6f10a8976
Create Date: 2023-11-04 10:56:32.750430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de136551882f'
down_revision = '81f6f10a8976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('Tersedia', 'Tidak Tersedia', name='product_status'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
